/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.2.3-0-gc1071ab+c1071ab3197f9bbf718123ec5bbabf449b2f7bab

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY, UNLESS YOU KNOW WHAT YOU ARE DOING !!!!
*******************************************************************************/

#define OD_DEFINITION
#include "301/CO_ODinterface.h"
#include "OD_can_node_1.h"

#if CO_VERSION_MAJOR < 4
#error This Object dictionary is compatible with CANopenNode V4.0 and above!
#endif

/*******************************************************************************
    OD data initialization of all groups
*******************************************************************************/
OD_can_node_1_ATTR_PERSIST_COMM OD_can_node_1_PERSIST_COMM_t OD_can_node_1_PERSIST_COMM = {
    .x1000_deviceType = 0x00000000,
    .x1005_COB_ID_SYNCMessage = 0x00000080,
    .x1006_communicationCyclePeriod = 0x00000000,
    .x1007_synchronousWindowLength = 0x00000000,
    .x1012_COB_IDTimeStampObject = 0x00000100,
    .x1014_COB_ID_EMCY = 0x00000080,
    .x1015_inhibitTimeEMCY = 0x0000,
    .x1016_consumerHeartbeatTime_sub0 = 0x7F,
    .x1016_consumerHeartbeatTime = {0x000109C4, 0x000209C4, 0x000309C4, 0x000409C4, 0x000509C4, 0x000609C4, 0x000709C4, 0x000809C4, 0x000909C4, 0x000A09C4, 0x000B09C4, 0x000C09C4, 0x000D09C4, 0x000E09C4, 0x000F09C4, 0x001009C4, 0x001109C4, 0x001209C4, 0x001309C4, 0x001409C4, 0x001509C4, 0x001609C4, 0x001709C4, 0x001809C4, 0x001909C4, 0x001A09C4, 0x001B09C4, 0x001C09C4, 0x001D09C4, 0x001E09C4, 0x001F09C4, 0x002009C4, 0x002109C4, 0x002209C4, 0x002309C4, 0x002409C4, 0x002509C4, 0x002609C4, 0x002709C4, 0x002809C4, 0x002909C4, 0x002A09C4, 0x002B09C4, 0x002C09C4, 0x002D09C4, 0x002E09C4, 0x002F09C4, 0x003009C4, 0x003109C4, 0x003209C4, 0x003309C4, 0x003409C4, 0x003509C4, 0x003609C4, 0x003709C4, 0x003809C4, 0x003909C4, 0x003A09C4, 0x003B09C4, 0x003C09C4, 0x003D09C4, 0x003E09C4, 0x003F09C4, 0x004009C4, 0x004109C4, 0x004209C4, 0x004309C4, 0x004409C4, 0x004509C4, 0x004609C4, 0x004709C4, 0x004809C4, 0x004909C4, 0x004A09C4, 0x004B09C4, 0x004C09C4, 0x004D09C4, 0x004E09C4, 0x004F09C4, 0x005009C4, 0x005109C4, 0x005209C4, 0x005309C4, 0x005409C4, 0x005509C4, 0x005609C4, 0x005709C4, 0x005809C4, 0x005909C4, 0x005A09C4, 0x005B09C4, 0x005C09C4, 0x005D09C4, 0x005E09C4, 0x005F09C4, 0x006009C4, 0x006109C4, 0x006209C4, 0x006309C4, 0x006409C4, 0x006509C4, 0x006609C4, 0x006709C4, 0x006809C4, 0x006909C4, 0x006A09C4, 0x006B09C4, 0x006C09C4, 0x006D09C4, 0x006E09C4, 0x006F09C4, 0x007009C4, 0x007109C4, 0x007209C4, 0x007309C4, 0x007409C4, 0x007509C4, 0x007609C4, 0x007709C4, 0x007809C4, 0x007909C4, 0x007A09C4, 0x007B09C4, 0x007C09C4, 0x007D09C4, 0x007E09C4, 0x007F09C4},
    .x1017_producerHeartbeatTime = 0x03E8,
    .x1018_identity = {
        .highestSub_indexSupported = 0x04,
        .vendor_ID = 0x00000000,
        .productCode = 0x00000000,
        .revisionNumber = 0x00000000,
        .serialNumber = 0x00000000
    },
    .x1019_synchronousCounterOverflowValue = 0x00,
    .x1280_SDOClientParameter = {
        .highestSub_indexSupported = 0x03,
        .COB_IDClientToServerTx = 0x80000000,
        .COB_IDServerToClientRx = 0x80000000,
        .node_IDOfTheSDOServer = 0x01
    }
};

OD_can_node_1_ATTR_RAM OD_can_node_1_RAM_t OD_can_node_1_RAM = {
    .x1001_errorRegister = 0x00,
    .x1010_storeParameters_sub0 = 0x04,
    .x1010_storeParameters = {0x00000001, 0x00000001, 0x00000001, 0x00000001},
    .x1011_restoreDefaultParameters_sub0 = 0x04,
    .x1011_restoreDefaultParameters = {0x00000001, 0x00000001, 0x00000001, 0x00000001},
    .x1200_SDOServerParameter = {
        .highestSub_indexSupported = 0x02,
        .COB_IDClientToServerRx = 0x00000600,
        .COB_IDServerToClientTx = 0x00000580
    }
};



/*******************************************************************************
    All OD objects (constant definitions)
*******************************************************************************/
typedef struct {
    OD_obj_var_t o_1000_deviceType;
    OD_obj_var_t o_1001_errorRegister;
    OD_obj_array_t o_1003_pre_definedErrorField;
    OD_obj_var_t o_1005_COB_ID_SYNCMessage;
    OD_obj_var_t o_1006_communicationCyclePeriod;
    OD_obj_var_t o_1007_synchronousWindowLength;
    OD_obj_array_t o_1010_storeParameters;
    OD_obj_array_t o_1011_restoreDefaultParameters;
    OD_obj_var_t o_1012_COB_IDTimeStampObject;
    OD_obj_var_t o_1014_COB_ID_EMCY;
    OD_obj_var_t o_1015_inhibitTimeEMCY;
    OD_obj_array_t o_1016_consumerHeartbeatTime;
    OD_obj_var_t o_1017_producerHeartbeatTime;
    OD_obj_record_t o_1018_identity[5];
    OD_obj_var_t o_1019_synchronousCounterOverflowValue;
    OD_obj_record_t o_1200_SDOServerParameter[3];
    OD_obj_record_t o_1280_SDOClientParameter[4];
} OD_can_node_1Objs_t;

static CO_PROGMEM OD_can_node_1Objs_t OD_can_node_1Objs = {
    .o_1000_deviceType = {
        .dataOrig = &OD_can_node_1_PERSIST_COMM.x1000_deviceType,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 4
    },
    .o_1001_errorRegister = {
        .dataOrig = &OD_can_node_1_RAM.x1001_errorRegister,
        .attribute = ODA_SDO_R | ODA_TPDO,
        .dataLength = 1
    },
    .o_1003_pre_definedErrorField = {
        .dataOrig0 = NULL,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_RW,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1005_COB_ID_SYNCMessage = {
        .dataOrig = &OD_can_node_1_PERSIST_COMM.x1005_COB_ID_SYNCMessage,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1006_communicationCyclePeriod = {
        .dataOrig = &OD_can_node_1_PERSIST_COMM.x1006_communicationCyclePeriod,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1007_synchronousWindowLength = {
        .dataOrig = &OD_can_node_1_PERSIST_COMM.x1007_synchronousWindowLength,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1010_storeParameters = {
        .dataOrig0 = &OD_can_node_1_RAM.x1010_storeParameters_sub0,
        .dataOrig = &OD_can_node_1_RAM.x1010_storeParameters[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1011_restoreDefaultParameters = {
        .dataOrig0 = &OD_can_node_1_RAM.x1011_restoreDefaultParameters_sub0,
        .dataOrig = &OD_can_node_1_RAM.x1011_restoreDefaultParameters[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1012_COB_IDTimeStampObject = {
        .dataOrig = &OD_can_node_1_PERSIST_COMM.x1012_COB_IDTimeStampObject,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1014_COB_ID_EMCY = {
        .dataOrig = &OD_can_node_1_PERSIST_COMM.x1014_COB_ID_EMCY,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1015_inhibitTimeEMCY = {
        .dataOrig = &OD_can_node_1_PERSIST_COMM.x1015_inhibitTimeEMCY,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_1016_consumerHeartbeatTime = {
        .dataOrig0 = &OD_can_node_1_PERSIST_COMM.x1016_consumerHeartbeatTime_sub0,
        .dataOrig = &OD_can_node_1_PERSIST_COMM.x1016_consumerHeartbeatTime[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1017_producerHeartbeatTime = {
        .dataOrig = &OD_can_node_1_PERSIST_COMM.x1017_producerHeartbeatTime,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_1018_identity = {
        {
            .dataOrig = &OD_can_node_1_PERSIST_COMM.x1018_identity.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_can_node_1_PERSIST_COMM.x1018_identity.vendor_ID,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_can_node_1_PERSIST_COMM.x1018_identity.productCode,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_can_node_1_PERSIST_COMM.x1018_identity.revisionNumber,
            .subIndex = 3,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_can_node_1_PERSIST_COMM.x1018_identity.serialNumber,
            .subIndex = 4,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1019_synchronousCounterOverflowValue = {
        .dataOrig = &OD_can_node_1_PERSIST_COMM.x1019_synchronousCounterOverflowValue,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_1200_SDOServerParameter = {
        {
            .dataOrig = &OD_can_node_1_RAM.x1200_SDOServerParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_can_node_1_RAM.x1200_SDOServerParameter.COB_IDClientToServerRx,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_can_node_1_RAM.x1200_SDOServerParameter.COB_IDServerToClientTx,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1280_SDOClientParameter = {
        {
            .dataOrig = &OD_can_node_1_PERSIST_COMM.x1280_SDOClientParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_can_node_1_PERSIST_COMM.x1280_SDOClientParameter.COB_IDClientToServerTx,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_can_node_1_PERSIST_COMM.x1280_SDOClientParameter.COB_IDServerToClientRx,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_can_node_1_PERSIST_COMM.x1280_SDOClientParameter.node_IDOfTheSDOServer,
            .subIndex = 3,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    }
};


/*******************************************************************************
    Object dictionary
*******************************************************************************/
static OD_can_node_1_ATTR_OD OD_entry_t OD_can_node_1List[] = {
    {0x1000, 0x01, ODT_VAR, &OD_can_node_1Objs.o_1000_deviceType, NULL},
    {0x1001, 0x01, ODT_VAR, &OD_can_node_1Objs.o_1001_errorRegister, NULL},
    {0x1003, 0x11, ODT_ARR, &OD_can_node_1Objs.o_1003_pre_definedErrorField, NULL},
    {0x1005, 0x01, ODT_VAR, &OD_can_node_1Objs.o_1005_COB_ID_SYNCMessage, NULL},
    {0x1006, 0x01, ODT_VAR, &OD_can_node_1Objs.o_1006_communicationCyclePeriod, NULL},
    {0x1007, 0x01, ODT_VAR, &OD_can_node_1Objs.o_1007_synchronousWindowLength, NULL},
    {0x1010, 0x05, ODT_ARR, &OD_can_node_1Objs.o_1010_storeParameters, NULL},
    {0x1011, 0x05, ODT_ARR, &OD_can_node_1Objs.o_1011_restoreDefaultParameters, NULL},
    {0x1012, 0x01, ODT_VAR, &OD_can_node_1Objs.o_1012_COB_IDTimeStampObject, NULL},
    {0x1014, 0x01, ODT_VAR, &OD_can_node_1Objs.o_1014_COB_ID_EMCY, NULL},
    {0x1015, 0x01, ODT_VAR, &OD_can_node_1Objs.o_1015_inhibitTimeEMCY, NULL},
    {0x1016, 0x80, ODT_ARR, &OD_can_node_1Objs.o_1016_consumerHeartbeatTime, NULL},
    {0x1017, 0x01, ODT_VAR, &OD_can_node_1Objs.o_1017_producerHeartbeatTime, NULL},
    {0x1018, 0x05, ODT_REC, &OD_can_node_1Objs.o_1018_identity, NULL},
    {0x1019, 0x01, ODT_VAR, &OD_can_node_1Objs.o_1019_synchronousCounterOverflowValue, NULL},
    {0x1200, 0x03, ODT_REC, &OD_can_node_1Objs.o_1200_SDOServerParameter, NULL},
    {0x1280, 0x04, ODT_REC, &OD_can_node_1Objs.o_1280_SDOClientParameter, NULL},
    {0x0000, 0x00, 0, NULL, NULL}
};

static OD_t _OD_can_node_1 = {
    (sizeof(OD_can_node_1List) / sizeof(OD_can_node_1List[0])) - 1,
    &OD_can_node_1List[0]
};

OD_t *OD_can_node_1 = &_OD_can_node_1;
