/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.2.3-0-gc1071ab+c1071ab3197f9bbf718123ec5bbabf449b2f7bab

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY !!!!
********************************************************************************

    File info:
        File Names:   OD_can_node_1.h; OD_can_node_1.c
        Project File: can_node_1.xpd
        File Version: 1

        Created:      23-11-2020 16:30:00
        Created By:   
        Modified:     09-07-2026 11:49:32
        Modified By:  

    Device Info:
        Vendor Name:  
        Vendor ID:    
        Product Name: New Product
        Product ID:   

        Description:  
*******************************************************************************/

#ifndef OD_can_node_1_H
#define OD_can_node_1_H
/*******************************************************************************
    Counters of OD objects
*******************************************************************************/
#define OD_can_node_1_CNT_NMT 1
#define OD_can_node_1_CNT_EM 1
#define OD_can_node_1_CNT_SYNC 1
#define OD_can_node_1_CNT_SYNC_PROD 1
#define OD_can_node_1_CNT_STORAGE 1
#define OD_can_node_1_CNT_TIME 1
#define OD_can_node_1_CNT_EM_PROD 1
#define OD_can_node_1_CNT_HB_CONS 1
#define OD_can_node_1_CNT_HB_PROD 1
#define OD_can_node_1_CNT_SDO_SRV 1
#define OD_can_node_1_CNT_SDO_CLI 1


/*******************************************************************************
    Sizes of OD arrays
*******************************************************************************/
#define OD_can_node_1_CNT_ARR_1003 16
#define OD_can_node_1_CNT_ARR_1010 4
#define OD_can_node_1_CNT_ARR_1011 4
#define OD_can_node_1_CNT_ARR_1016 127


/*******************************************************************************
    OD data declaration of all groups
*******************************************************************************/
typedef struct {
    uint32_t x1000_deviceType;
    uint32_t x1005_COB_ID_SYNCMessage;
    uint32_t x1006_communicationCyclePeriod;
    uint32_t x1007_synchronousWindowLength;
    uint32_t x1012_COB_IDTimeStampObject;
    uint32_t x1014_COB_ID_EMCY;
    uint16_t x1015_inhibitTimeEMCY;
    uint8_t x1016_consumerHeartbeatTime_sub0;
    uint32_t x1016_consumerHeartbeatTime[OD_can_node_1_CNT_ARR_1016];
    uint16_t x1017_producerHeartbeatTime;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t vendor_ID;
        uint32_t productCode;
        uint32_t revisionNumber;
        uint32_t serialNumber;
    } x1018_identity;
    uint8_t x1019_synchronousCounterOverflowValue;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDClientToServerTx;
        uint32_t COB_IDServerToClientRx;
        uint8_t node_IDOfTheSDOServer;
    } x1280_SDOClientParameter;
} OD_can_node_1_PERSIST_COMM_t;

typedef struct {
    uint8_t x1001_errorRegister;
    uint8_t x1010_storeParameters_sub0;
    uint32_t x1010_storeParameters[OD_can_node_1_CNT_ARR_1010];
    uint8_t x1011_restoreDefaultParameters_sub0;
    uint32_t x1011_restoreDefaultParameters[OD_can_node_1_CNT_ARR_1011];
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDClientToServerRx;
        uint32_t COB_IDServerToClientTx;
    } x1200_SDOServerParameter;
} OD_can_node_1_RAM_t;

#ifndef OD_can_node_1_ATTR_PERSIST_COMM
#define OD_can_node_1_ATTR_PERSIST_COMM
#endif
extern OD_can_node_1_ATTR_PERSIST_COMM OD_can_node_1_PERSIST_COMM_t OD_can_node_1_PERSIST_COMM;

#ifndef OD_can_node_1_ATTR_RAM
#define OD_can_node_1_ATTR_RAM
#endif
extern OD_can_node_1_ATTR_RAM OD_can_node_1_RAM_t OD_can_node_1_RAM;

#ifndef OD_can_node_1_ATTR_OD
#define OD_can_node_1_ATTR_OD
#endif
extern OD_can_node_1_ATTR_OD OD_t *OD_can_node_1;


/*******************************************************************************
    Object dictionary entries - shortcuts
*******************************************************************************/
#define OD_can_node_1_ENTRY_H1000 &OD_can_node_1->list[0]
#define OD_can_node_1_ENTRY_H1001 &OD_can_node_1->list[1]
#define OD_can_node_1_ENTRY_H1003 &OD_can_node_1->list[2]
#define OD_can_node_1_ENTRY_H1005 &OD_can_node_1->list[3]
#define OD_can_node_1_ENTRY_H1006 &OD_can_node_1->list[4]
#define OD_can_node_1_ENTRY_H1007 &OD_can_node_1->list[5]
#define OD_can_node_1_ENTRY_H1010 &OD_can_node_1->list[6]
#define OD_can_node_1_ENTRY_H1011 &OD_can_node_1->list[7]
#define OD_can_node_1_ENTRY_H1012 &OD_can_node_1->list[8]
#define OD_can_node_1_ENTRY_H1014 &OD_can_node_1->list[9]
#define OD_can_node_1_ENTRY_H1015 &OD_can_node_1->list[10]
#define OD_can_node_1_ENTRY_H1016 &OD_can_node_1->list[11]
#define OD_can_node_1_ENTRY_H1017 &OD_can_node_1->list[12]
#define OD_can_node_1_ENTRY_H1018 &OD_can_node_1->list[13]
#define OD_can_node_1_ENTRY_H1019 &OD_can_node_1->list[14]
#define OD_can_node_1_ENTRY_H1200 &OD_can_node_1->list[15]
#define OD_can_node_1_ENTRY_H1280 &OD_can_node_1->list[16]


/*******************************************************************************
    Object dictionary entries - shortcuts with names
*******************************************************************************/
#define OD_can_node_1_ENTRY_H1000_deviceType &OD_can_node_1->list[0]
#define OD_can_node_1_ENTRY_H1001_errorRegister &OD_can_node_1->list[1]
#define OD_can_node_1_ENTRY_H1003_pre_definedErrorField &OD_can_node_1->list[2]
#define OD_can_node_1_ENTRY_H1005_COB_ID_SYNCMessage &OD_can_node_1->list[3]
#define OD_can_node_1_ENTRY_H1006_communicationCyclePeriod &OD_can_node_1->list[4]
#define OD_can_node_1_ENTRY_H1007_synchronousWindowLength &OD_can_node_1->list[5]
#define OD_can_node_1_ENTRY_H1010_storeParameters &OD_can_node_1->list[6]
#define OD_can_node_1_ENTRY_H1011_restoreDefaultParameters &OD_can_node_1->list[7]
#define OD_can_node_1_ENTRY_H1012_COB_IDTimeStampObject &OD_can_node_1->list[8]
#define OD_can_node_1_ENTRY_H1014_COB_ID_EMCY &OD_can_node_1->list[9]
#define OD_can_node_1_ENTRY_H1015_inhibitTimeEMCY &OD_can_node_1->list[10]
#define OD_can_node_1_ENTRY_H1016_consumerHeartbeatTime &OD_can_node_1->list[11]
#define OD_can_node_1_ENTRY_H1017_producerHeartbeatTime &OD_can_node_1->list[12]
#define OD_can_node_1_ENTRY_H1018_identity &OD_can_node_1->list[13]
#define OD_can_node_1_ENTRY_H1019_synchronousCounterOverflowValue &OD_can_node_1->list[14]
#define OD_can_node_1_ENTRY_H1200_SDOServerParameter &OD_can_node_1->list[15]
#define OD_can_node_1_ENTRY_H1280_SDOClientParameter &OD_can_node_1->list[16]


/*******************************************************************************
    OD config structure
*******************************************************************************/
#ifdef CO_MULTIPLE_OD
#define OD_can_node_1_INIT_CONFIG(config) {\
    (config).CNT_NMT = OD_can_node_1_CNT_NMT;\
    (config).ENTRY_H1017 = OD_can_node_1_ENTRY_H1017;\
    (config).CNT_HB_CONS = OD_can_node_1_CNT_HB_CONS;\
    (config).CNT_ARR_1016 = OD_can_node_1_CNT_ARR_1016;\
    (config).ENTRY_H1016 = OD_can_node_1_ENTRY_H1016;\
    (config).CNT_EM = OD_can_node_1_CNT_EM;\
    (config).ENTRY_H1001 = OD_can_node_1_ENTRY_H1001;\
    (config).ENTRY_H1014 = OD_can_node_1_ENTRY_H1014;\
    (config).ENTRY_H1015 = OD_can_node_1_ENTRY_H1015;\
    (config).CNT_ARR_1003 = OD_can_node_1_CNT_ARR_1003;\
    (config).ENTRY_H1003 = OD_can_node_1_ENTRY_H1003;\
    (config).CNT_SDO_SRV = OD_can_node_1_CNT_SDO_SRV;\
    (config).ENTRY_H1200 = OD_can_node_1_ENTRY_H1200;\
    (config).CNT_SDO_CLI = OD_can_node_1_CNT_SDO_CLI;\
    (config).ENTRY_H1280 = OD_can_node_1_ENTRY_H1280;\
    (config).CNT_TIME = OD_can_node_1_CNT_TIME;\
    (config).ENTRY_H1012 = OD_can_node_1_ENTRY_H1012;\
    (config).CNT_SYNC = OD_can_node_1_CNT_SYNC;\
    (config).ENTRY_H1005 = OD_can_node_1_ENTRY_H1005;\
    (config).ENTRY_H1006 = OD_can_node_1_ENTRY_H1006;\
    (config).ENTRY_H1007 = OD_can_node_1_ENTRY_H1007;\
    (config).ENTRY_H1019 = OD_can_node_1_ENTRY_H1019;\
    (config).CNT_RPDO = 0;\
    (config).ENTRY_H1400 = NULL;\
    (config).ENTRY_H1600 = NULL;\
    (config).CNT_TPDO = 0;\
    (config).ENTRY_H1800 = NULL;\
    (config).ENTRY_H1A00 = NULL;\
    (config).CNT_LEDS = 0;\
    (config).CNT_GFC = 0;\
    (config).ENTRY_H1300 = NULL;\
    (config).CNT_SRDO = 0;\
    (config).ENTRY_H1301 = NULL;\
    (config).ENTRY_H1381 = NULL;\
    (config).ENTRY_H13FE = NULL;\
    (config).ENTRY_H13FF = NULL;\
    (config).CNT_LSS_SLV = 0;\
    (config).CNT_LSS_MST = 0;\
    (config).CNT_GTWA = 0;\
    (config).CNT_TRACE = 0;\
}
#endif

#endif /* OD_can_node_1_H */
